// export enum FEEDBACK_ISSUE {
//   ISSUE_1 = 'ISSUE_1',
//   ISSUE_2 = 'ISSUE_2',
//   ISSUE_3 = 'ISSUE_3',
//   ISSUE_4 = 'ISSUE_4',
//   ISSUE_5 = 'ISSUE_5',
//   ISSUE_6 = 'ISSUE_6',
//   ISSUE_7 = 'ISSUE_7',
//   ISSUE_8 = 'ISSUE_8',
//   ISSUE_9 = 'ISSUE_9',
//   ISSUE_10 = 'ISSUE_10',
//   ISSUE_11 = 'ISSUE_11',
//   ISSUE_12 = 'ISSUE_12',
// }

// export const POSITIVE_FEEDBACK_ISSUES = [
//   FEEDBACK_ISSUE.ISSUE_1, FEEDBACK_ISSUE.ISSUE_2, FEEDBACK_ISSUE.ISSUE_3,
//   FEEDBACK_ISSUE.ISSUE_4, FEEDBACK_ISSUE.ISSUE_5, FEEDBACK_ISSUE.ISSUE_6,
// ];
//
// export const NEGATIVE_FEEDBACK_ISSUES = [
//   FEEDBACK_ISSUE.ISSUE_7, FEEDBACK_ISSUE.ISSUE_8, FEEDBACK_ISSUE.ISSUE_9,
//   FEEDBACK_ISSUE.ISSUE_10, FEEDBACK_ISSUE.ISSUE_11, FEEDBACK_ISSUE.ISSUE_12,
// ];

export const MIN_LENGTH_COMMENT = 10;
