export const MESSAGE_MAP = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
  REQUEST_CONFIRM_CODE_LIMIT: 'REQUEST_CONFIRM_CODE_LIMIT',
  CODE_NOT_FOUND: 'CODE_NOT_FOUND',
} as const;
