export const MESSAGE_MAP = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
  REQUEST_CONFIRM_CODE_LIMIT: 'REQUEST_CONFIRM_CODE_LIMIT',
  CODE_NOT_FOUND: 'CODE_NOT_FOUND',
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
  INVALID_IMAGES_FORMAT: 'INVALID_IMAGES_FORMAT',
} as const;
