export const CRITERIONS: Record<string, string> = {
  atmosphere_good: 'Атмосфера',
  pricing_good: 'Ценовая политика',
  service_good: 'Сервис',
  menu_good: 'Меню',
  kitchen_good: 'Кухня',
  additional_good: 'Дополнительные удобства',
  atmosphere_bad: 'Атмосфера',
  pricing_bad: 'Ценовая политика',
  service_bad: 'Сервис',
  menu_bad: 'Меню',
  kitchen_bad: 'Кухня',
  additional_bad: 'Дополнительные удобства',
  service_bad_2: 'Сервис',
  price_bad: 'Ценовая политика',
  atmosphere_bad_2: 'Атмосфера',
  location_bad: 'Расположение',
  service_good_2: 'Сервис',
  price_good: 'Ценовая политика',
  atmosphere_good_2: 'Атмосфера',
  location_good: 'Расположение',
};
