name: deploy

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run:
          npm i
          npm run build --if-present
          pm2 stop 0
          pm2 start 0
          pm2 save

